"""XML writer: MapXml → PGM map.xml string.

Roundtrip notes
---------------
- Named regions and filters that are children of exactly one composite are
  written **inline** inside that parent (with their id attribute preserved).
  PGM resolves ids from nested elements, so apply rules can still reference
  them by name.
- Entities referenced by **two or more** composites are promoted to
  top-level and referenced via ``<region id="X"/>`` / ``<filter id="X"/>``.
- **Synthetic ids** (those containing ``__anon_``, or starting with ``__``)
  are written **without** an id attribute, restoring them to the anonymous
  inline form they had in the original XML.
- Fields not captured during parsing (``<clear/>``, kit ``<effect>``
  elements, team ``max-overfill``, wool ``required``, etc.) are absent from
  the output.  The roundtrip is faithful for everything we do store.
- Coordinate values of ``None`` (lost template variables) are written as
  ``0``.  Infinity values are written as ``oo`` / ``-oo``.
"""

from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from typing import Optional

from .datatypes import (
    MapXml, Team, Author, Kit, KitItem, KitArmor, Spawn, Wool,
    WoolSpawner, SpawnerItem, Renewable, BlockDropRule, BlockDropItem, ApplyRule,
)
from .filters import (
    Filter, AllFilter, AnyFilter, OneFilter,
    NotFilter, DenyFilter, AllowFilter,
    TeamFilter, MaterialFilter, VoidFilter, CauseFilter,
    BlocksFilter, CarryingFilter, WearingFilter, HoldingFilter,
    AliveFilter, DeadFilter, ParticipatingFilter, ObservingFilter,
    MatchRunningFilter, MatchStartedFilter, GroundedFilter,
    NeverFilter, AlwaysFilter,
    TimeFilter, AfterFilter, PulseFilter,
    OffsetFilter, VariableFilter, CompletedFilter, ObjectiveFilter,
    FilterRef, KillStreakFilter, ClassFilter, RegionFilter, PlayerFilter,
)
from .regions import (
    Region, Rectangle, Cuboid, Cylinder, Circle, Sphere, Block, Point,
    Union, Negative, Complement, Intersect, Mirror, Translate,
    Half, Reference, Everywhere, Above,
)

# Built-in filter ids pre-seeded by FilterParser — never written to <filters>.
_BUILTIN_FILTER_IDS: frozenset[str] = frozenset({'never', 'always'})


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def to_xml(xml_data: MapXml, *, indent: bool = True) -> str:
    """Serialize MapXml to a PGM map.xml string."""
    root = _build_map_elem(xml_data)
    if indent:
        _indent(root)
    return '<?xml version="1.0"?>\n' + ET.tostring(root, encoding='unicode')


# ---------------------------------------------------------------------------
# Synthetic-id detection
# ---------------------------------------------------------------------------

def _is_synthetic(id_str: str) -> bool:
    """True if id_str was generated by the parser, not present in source XML."""
    return '__anon_' in id_str or id_str.startswith('__')


def _export_id(id_str: str) -> Optional[str]:
    """Return the id to write, or None to omit the id attribute."""
    return None if _is_synthetic(id_str) else id_str


# ---------------------------------------------------------------------------
# Coordinate helpers
# ---------------------------------------------------------------------------

def _coord(v) -> str:
    if v is None:
        return '0'
    if isinstance(v, float):
        if v == math.inf:
            return 'oo'
        if v == -math.inf:
            return '-oo'
    return str(int(v) if isinstance(v, float) and v == int(v) else v)


def _coords3(x, y, z) -> str:
    return f'{_coord(x)},{_coord(y)},{_coord(z)}'


def _coords2(x, z) -> str:
    return f'{_coord(x)},{_coord(z)}'


# ---------------------------------------------------------------------------
# Registry metadata: compute placement decisions
# ---------------------------------------------------------------------------

def _count_filter_parents(filters: dict[str, Filter]) -> dict[str, int]:
    """Return {filter_id: number_of_composite_parents}."""
    counts: dict[str, int] = {}
    for f in filters.values():
        if hasattr(f, 'children'):
            for cid in f.children:
                counts[cid] = counts.get(cid, 0) + 1
        if hasattr(f, 'child') and f.child:
            counts[f.child] = counts.get(f.child, 0) + 1
        # blocks / offset have a single 'child'
        if isinstance(f, (BlocksFilter, OffsetFilter)) and f.child:
            counts[f.child] = counts.get(f.child, 0) + 1
    return counts


def _count_region_parents(regions: dict[str, Region]) -> dict[str, int]:
    """Return {region_id: number_of_composite_parents}."""
    counts: dict[str, int] = {}
    for r in regions.values():
        if hasattr(r, 'children'):
            for cid in r.children:
                counts[cid] = counts.get(cid, 0) + 1
        if hasattr(r, 'source_id') and r.source_id:
            counts[r.source_id] = counts.get(r.source_id, 0) + 1
    return counts


def _external_region_refs(xml_data: MapXml) -> set[str]:
    """Collect all named region IDs referenced outside the region composite graph.

    Includes references from spawners, renewables, block-drop rules, apply
    rules, and wool monument region ids.  Any region in this set must be
    written at top-level so that external references resolve correctly, even
    when the region is also a child of exactly one composite.
    """
    refs: set[str] = set()
    for s in xml_data.spawners:
        refs.add(s.spawn_region)
        refs.add(s.player_region)
    for r in xml_data.renewables:
        if r.region_id:
            refs.add(r.region_id)
    for r in xml_data.block_drop_rules:
        if r.region_id:
            refs.add(r.region_id)
    for rule in xml_data.apply_rules:
        if rule.region_id and not _is_synthetic(rule.region_id):
            refs.add(rule.region_id)
    for wool in xml_data.wools:
        if wool.monument_region_id:
            refs.add(wool.monument_region_id)
    return refs


# ---------------------------------------------------------------------------
# Top-level element builder
# ---------------------------------------------------------------------------

def _build_map_elem(xml_data: MapXml) -> ET.Element:
    root = ET.Element('map', proto='1.5.0')

    ET.SubElement(root, 'name').text = xml_data.name
    ET.SubElement(root, 'version').text = xml_data.version
    if xml_data.gamemode and xml_data.gamemode != 'ctw':
        ET.SubElement(root, 'gamemode').text = xml_data.gamemode
    ET.SubElement(root, 'objective').text = xml_data.objective

    _write_authors(root, xml_data.authors)
    _write_teams(root, xml_data.teams)
    _write_kits(root, xml_data.kits)
    _write_spawns(root, xml_data.spawns, xml_data.observer_spawn, xml_data.regions)
    _write_wools(root, xml_data.wools)

    if xml_data.filters:
        _write_filters_block(root, xml_data.filters)

    if xml_data.regions or xml_data.apply_rules:
        _write_regions_block(root, xml_data.regions, xml_data.apply_rules,
                             _external_region_refs(xml_data))

    if xml_data.spawners:
        _write_spawners(root, xml_data.spawners)
    if xml_data.renewables:
        _write_renewables(root, xml_data.renewables)
    if xml_data.block_drop_rules:
        _write_block_drops(root, xml_data.block_drop_rules)

    if xml_data.max_build_height is not None:
        ET.SubElement(root, 'maxbuildheight').text = str(xml_data.max_build_height)

    return root


# ---------------------------------------------------------------------------
# Authors
# ---------------------------------------------------------------------------

def _write_authors(parent: ET.Element, authors: list[Author]) -> None:
    auth_list = [a for a in authors if a.role == 'author']
    contrib_list = [a for a in authors if a.role == 'contributor']

    if auth_list:
        block = ET.SubElement(parent, 'authors')
        for a in auth_list:
            attrs: dict = {'uuid': a.uuid}
            if a.contribution:
                attrs['contribution'] = a.contribution
            ET.SubElement(block, 'author', **attrs)

    if contrib_list:
        block = ET.SubElement(parent, 'contributors')
        for a in contrib_list:
            attrs = {'uuid': a.uuid}
            if a.contribution:
                attrs['contribution'] = a.contribution
            ET.SubElement(block, 'contributor', **attrs)


# ---------------------------------------------------------------------------
# Teams
# ---------------------------------------------------------------------------

def _write_teams(parent: ET.Element, teams: list[Team]) -> None:
    if not teams:
        return
    block = ET.SubElement(parent, 'teams')
    for team in teams:
        attrs: dict = {'id': team.id, 'color': team.color}
        if team.dye_color:
            attrs['dye-color'] = team.dye_color
        if team.max_players:
            attrs['max'] = str(team.max_players)
        if team.min_players:
            attrs['min'] = str(team.min_players)
        elem = ET.SubElement(block, 'team', **attrs)
        elem.text = team.name


# ---------------------------------------------------------------------------
# Kits
# ---------------------------------------------------------------------------

def _write_kits(parent: ET.Element, kits: list[Kit]) -> None:
    if not kits:
        return
    block = ET.SubElement(parent, 'kits')
    for kit in kits:
        kit_elem = ET.SubElement(block, 'kit', id=kit.id)
        for item in kit.items:
            _write_kit_item(kit_elem, item)
        for armor in kit.armor:
            _write_kit_armor(kit_elem, armor)


def _write_kit_item(parent: ET.Element, item: KitItem) -> None:
    attrs: dict = {'slot': str(item.slot), 'material': item.material}
    if item.amount != 1:
        attrs['amount'] = str(item.amount)
    if item.item_damage:
        attrs['damage'] = str(item.item_damage)
    if item.unbreakable:
        attrs['unbreakable'] = 'true'
    if item.team_color:
        attrs['team-color'] = 'true'
    elem = ET.SubElement(parent, 'item', **attrs)
    _write_enchantments(elem, item.enchantments)


def _write_kit_armor(parent: ET.Element, armor: KitArmor) -> None:
    attrs: dict = {'material': armor.material}
    if armor.unbreakable:
        attrs['unbreakable'] = 'true'
    if armor.team_color:
        attrs['team-color'] = 'true'
    elem = ET.SubElement(parent, armor.slot_name, **attrs)
    _write_enchantments(elem, armor.enchantments)


def _write_enchantments(parent: ET.Element, enchantments: str) -> None:
    if not enchantments:
        return
    for token in enchantments.split(','):
        token = token.strip()
        if not token:
            continue
        if ':' in token:
            name, _, level = token.rpartition(':')
            enc = ET.SubElement(parent, 'enchantment', level=level)
            enc.text = name
        else:
            ET.SubElement(parent, 'enchantment').text = token


# ---------------------------------------------------------------------------
# Spawns
# ---------------------------------------------------------------------------

def _write_spawns(
    parent: ET.Element,
    spawns: list[Spawn],
    observer_spawn: Optional[Spawn],
    regions: dict[str, Region],
) -> None:
    if not spawns and observer_spawn is None:
        return
    block = ET.SubElement(parent, 'spawns')
    if observer_spawn is not None:
        _write_spawn_elem(block, observer_spawn, 'default', regions)
    for spawn in spawns:
        _write_spawn_elem(block, spawn, 'spawn', regions)


def _write_spawn_elem(
    parent: ET.Element, spawn: Spawn, tag: str, regions: dict[str, Region]
) -> None:
    attrs: dict = {}
    if spawn.team:
        attrs['team'] = spawn.team
    if spawn.kit:
        attrs['kit'] = spawn.kit
    if spawn.yaw:
        attrs['yaw'] = _coord(spawn.yaw)

    region = spawn.region
    if region is not None and not _is_synthetic(region.id):
        # Named region — use region= attribute
        attrs['region'] = region.id
        ET.SubElement(parent, tag, **attrs)
    else:
        elem = ET.SubElement(parent, tag, **attrs)
        if region is not None:
            region_container = ET.SubElement(elem, 'region')
            # Inline the actual region element without id
            region_container.append(_region_elem_inline(region))


# ---------------------------------------------------------------------------
# Wools
# ---------------------------------------------------------------------------

def _write_wools(parent: ET.Element, wools: list[Wool]) -> None:
    if not wools:
        return
    block = ET.SubElement(parent, 'wools')
    for wool in wools:
        attrs: dict = {
            'team': wool.team,
            'color': wool.color,
            'location': _coords3(*wool.location),
        }
        if wool.monument_region_id:
            attrs['monument'] = wool.monument_region_id
        elem = ET.SubElement(block, 'wool', **attrs)
        if not wool.monument_region_id:
            mon = ET.SubElement(elem, 'monument')
            blk = ET.SubElement(mon, 'block')
            blk.text = _coords3(*wool.monument)


# ---------------------------------------------------------------------------
# Filters block
# ---------------------------------------------------------------------------

def _write_filters_block(parent: ET.Element, filters: dict[str, Filter]) -> None:
    parent_counts = _count_filter_parents(filters)

    # Determine which filters are top-level:
    # - not a child of any composite (root), OR
    # - referenced by 2+ composites (must be top-level to avoid duplicate inline)
    top_level_ids: set[str] = set()
    for fid in filters:
        if fid in _BUILTIN_FILTER_IDS or _is_synthetic(fid):
            continue
        count = parent_counts.get(fid, 0)
        if count == 0 or count >= 2:
            top_level_ids.add(fid)

    if not top_level_ids:
        return

    block = ET.SubElement(parent, 'filters')
    for fid in filters:
        if fid not in top_level_ids:
            continue
        elem = _filter_elem(fid, filters, parent_counts, top_level_ids, with_id=True)
        if elem is not None:
            block.append(elem)


def _filter_child_elem(
    child_id: str,
    filters: dict[str, Filter],
    parent_counts: dict[str, int],
    top_level_ids: set[str],
) -> Optional[ET.Element]:
    """Serialize a filter child: reference for top-level ids, inline otherwise."""
    if child_id in top_level_ids:
        return ET.Element('filter', id=child_id)
    # Synthetic or single-parent: inline without id (or with id if non-synthetic)
    child = filters.get(child_id)
    if child is None:
        return ET.Element('filter', id=child_id)
    return _filter_elem(child_id, filters, parent_counts, top_level_ids, with_id=not _is_synthetic(child_id))


def _filter_elem(
    fid: str,
    filters: dict[str, Filter],
    parent_counts: dict[str, int],
    top_level_ids: set[str],
    with_id: bool = True,
) -> Optional[ET.Element]:
    """Build an XML element for a filter."""
    f = filters.get(fid)
    if f is None:
        return None

    def _child(child_id: str) -> Optional[ET.Element]:
        return _filter_child_elem(child_id, filters, parent_counts, top_level_ids)

    attrs: dict = {}
    if with_id and fid and not _is_synthetic(fid):
        attrs['id'] = fid

    if isinstance(f, (AllFilter, AnyFilter, OneFilter)):
        tag = f.filter_type
        elem = ET.Element(tag, **attrs)
        for cid in f.children:
            child_e = _child(cid)
            if child_e is not None:
                elem.append(child_e)
        return elem

    elif isinstance(f, (NotFilter, DenyFilter, AllowFilter)):
        tag = f.filter_type
        elem = ET.Element(tag, **attrs)
        if f.child:
            child_e = _child(f.child)
            if child_e is not None:
                elem.append(child_e)
        return elem

    elif isinstance(f, TeamFilter):
        elem = ET.Element('team', **attrs)
        elem.text = f.team
        return elem

    elif isinstance(f, MaterialFilter):
        elem = ET.Element('material', **attrs)
        elem.text = f.material
        return elem

    elif isinstance(f, VoidFilter):
        return ET.Element('void', **attrs)

    elif isinstance(f, CauseFilter):
        elem = ET.Element('cause', **attrs)
        elem.text = f.cause
        return elem

    elif isinstance(f, BlocksFilter):
        a = {**attrs, 'region': f.region} if f.region else attrs
        elem = ET.Element('blocks', **a)
        if f.child:
            child_e = _child(f.child)
            if child_e is not None:
                elem.append(child_e)
        return elem

    elif isinstance(f, (CarryingFilter, WearingFilter, HoldingFilter)):
        tag = f.filter_type
        extra: dict = {}
        if isinstance(f, CarryingFilter):
            if f.ignore_metadata:
                extra['ignore-metadata'] = 'true'
            if not f.ignore_durability:
                extra['ignore-durability'] = 'false'
        elif isinstance(f, WearingFilter):
            if f.ignore_metadata:
                extra['ignore-metadata'] = 'true'
        elem = ET.Element(tag, **{**attrs, **extra})
        item_attrs: dict = {'material': f.material}
        if f.damage is not None:
            item_attrs['damage'] = str(f.damage)
        if hasattr(f, 'enchantments') and f.enchantments:
            item_attrs['enchantment'] = f.enchantments
        ET.SubElement(elem, 'item', **item_attrs)
        return elem

    elif isinstance(f, AliveFilter):
        return ET.Element('alive', **attrs)
    elif isinstance(f, DeadFilter):
        return ET.Element('dead', **attrs)
    elif isinstance(f, ParticipatingFilter):
        return ET.Element('participating', **attrs)
    elif isinstance(f, ObservingFilter):
        return ET.Element('observing', **attrs)
    elif isinstance(f, MatchRunningFilter):
        return ET.Element('match-running', **attrs)
    elif isinstance(f, MatchStartedFilter):
        return ET.Element('match-started', **attrs)
    elif isinstance(f, GroundedFilter):
        return ET.Element('grounded', **attrs)
    elif isinstance(f, NeverFilter):
        return ET.Element('never', **attrs)
    elif isinstance(f, AlwaysFilter):
        return ET.Element('always', **attrs)

    elif isinstance(f, TimeFilter):
        elem = ET.Element('time', **attrs)
        elem.text = f.duration
        return elem

    elif isinstance(f, AfterFilter):
        a = {**attrs}
        if f.filter_ref:
            a['filter'] = f.filter_ref
        if f.duration:
            a['duration'] = f.duration
        return ET.Element('after', **a)

    elif isinstance(f, PulseFilter):
        a = {**attrs}
        if f.period:
            a['period'] = f.period
        if f.duration:
            a['duration'] = f.duration
        if f.filter_ref:
            a['filter'] = f.filter_ref
        return ET.Element('pulse', **a)

    elif isinstance(f, OffsetFilter):
        a = {**attrs, 'vector': f.vector}
        elem = ET.Element('offset', **a)
        if f.child:
            child_e = _child(f.child)
            if child_e is not None:
                elem.append(child_e)
        return elem

    elif isinstance(f, VariableFilter):
        a = {**attrs, 'var': f.var}
        if f.team:
            a['team'] = f.team
        elem = ET.Element('variable', **a)
        elem.text = f.value
        return elem

    elif isinstance(f, (CompletedFilter, ObjectiveFilter)):
        tag = 'completed' if isinstance(f, CompletedFilter) else 'objective'
        elem = ET.Element(tag, **attrs)
        elem.text = f.objective
        return elem

    elif isinstance(f, KillStreakFilter):
        a = {**attrs}
        if f.min is not None:
            a['min'] = str(f.min)
        if f.max is not None:
            a['max'] = str(f.max)
        if f.count is not None:
            a['count'] = str(f.count)
        return ET.Element('kill-streak', **a)

    elif isinstance(f, ClassFilter):
        elem = ET.Element('class', **attrs)
        elem.text = f.name
        return elem

    elif isinstance(f, RegionFilter):
        return ET.Element('region', **{**attrs, 'id': f.region} if f.region else attrs)

    elif isinstance(f, PlayerFilter):
        a = {**attrs}
        if f.min is not None:
            a['min'] = str(f.min)
        if f.max is not None:
            a['max'] = str(f.max)
        return ET.Element('players', **a)

    return None


# ---------------------------------------------------------------------------
# Regions block
# ---------------------------------------------------------------------------

def _write_regions_block(
    parent: ET.Element,
    regions: dict[str, Region],
    apply_rules: list[ApplyRule],
    external_refs: set[str] | None = None,
) -> None:
    parent_counts = _count_region_parents(regions)
    external = external_refs or set()

    # Top-level: root regions (0 parents) + multi-parent regions (2+)
    # + any region referenced externally (spawners, renewables, etc.)
    top_level_ids: set[str] = set()
    for rid in regions:
        if _is_synthetic(rid):
            continue
        count = parent_counts.get(rid, 0)
        if count == 0 or count >= 2 or rid in external:
            top_level_ids.add(rid)

    # A mirror/translate writes a named source as a region="<id>" reference, which
    # only resolves if that source is also written top-level. A named source with a
    # single parent would otherwise be inlined-by-reference and lost on re-parse.
    for r in regions.values():
        sid = getattr(r, 'source_id', '')
        if sid and not _is_synthetic(sid) and sid in regions:
            top_level_ids.add(sid)

    block = ET.SubElement(parent, 'regions')

    for rid in regions:
        if rid not in top_level_ids:
            continue
        elem = _region_elem(rid, regions, parent_counts, top_level_ids, with_id=True)
        if elem is not None:
            block.append(elem)

    for i, rule in enumerate(apply_rules):
        block.append(_apply_elem(rule, regions, parent_counts, top_level_ids, i))


def _region_child_elem(
    child_id: str,
    regions: dict[str, Region],
    parent_counts: dict[str, int],
    top_level_ids: set[str],
) -> ET.Element:
    """Reference for top-level ids, inline otherwise."""
    if child_id in top_level_ids:
        return ET.Element('region', id=child_id)
    child = regions.get(child_id)
    if child is None:
        return ET.Element('region', id=child_id)
    return _region_elem(child_id, regions, parent_counts, top_level_ids,
                        with_id=not _is_synthetic(child_id))


def _region_elem(
    rid: str,
    regions: dict[str, Region],
    parent_counts: dict[str, int],
    top_level_ids: set[str],
    with_id: bool = True,
) -> Optional[ET.Element]:
    """Build an XML element for a region."""
    r = regions.get(rid)
    if r is None:
        return None

    def _child(child_id: str) -> ET.Element:
        return _region_child_elem(child_id, regions, parent_counts, top_level_ids)

    attrs: dict = {}
    if with_id and rid and not _is_synthetic(rid):
        attrs['id'] = rid

    if isinstance(r, Rectangle):
        return ET.Element('rectangle', **{
            **attrs,
            'min': _coords2(r.min_x, r.min_z),
            'max': _coords2(r.max_x, r.max_z),
        })

    elif isinstance(r, Cuboid):
        return ET.Element('cuboid', **{
            **attrs,
            'min': _coords3(r.min_x, r.min_y, r.min_z),
            'max': _coords3(r.max_x, r.max_y, r.max_z),
        })

    elif isinstance(r, Cylinder):
        a = {
            **attrs,
            'base': _coords3(r.base_x, r.base_y, r.base_z),
            'radius': _coord(r.radius),
        }
        if r.height is not None:
            a['height'] = _coord(r.height)
        return ET.Element('cylinder', **a)

    elif isinstance(r, Circle):
        return ET.Element('circle', **{
            **attrs,
            'center': _coords2(r.center_x, r.center_z),
            'radius': _coord(r.radius),
        })

    elif isinstance(r, Sphere):
        return ET.Element('sphere', **{
            **attrs,
            'origin': _coords3(r.origin_x, r.origin_y, r.origin_z),
            'radius': _coord(r.radius),
        })

    elif isinstance(r, Block):
        elem = ET.Element('block', **attrs)
        elem.text = _coords3(r.x, r.y, r.z)
        return elem

    elif isinstance(r, Point):
        elem = ET.Element('point', **attrs)
        elem.text = _coords3(r.x, r.y, r.z)
        return elem

    elif isinstance(r, (Union, Negative, Complement, Intersect)):
        tag = r.region_type
        elem = ET.Element(tag, **attrs)
        for cid in r.children:
            elem.append(_child(cid))
        return elem

    elif isinstance(r, Mirror):
        a = {
            **attrs,
            'origin': _coords3(r.origin_x, r.origin_y, r.origin_z),
            'normal': _coords3(r.normal_x, r.normal_y, r.normal_z),
        }
        if r.source_id and not _is_synthetic(r.source_id):
            a['region'] = r.source_id
        elem = ET.Element('mirror', **a)
        if r.source_id and _is_synthetic(r.source_id):
            source_elem = regions.get(r.source_id)
            if source_elem is not None:
                elem.append(_region_elem_inline(source_elem))
        return elem

    elif isinstance(r, Translate):
        a = {
            **attrs,
            'offset': _coords3(r.offset_x, r.offset_y, r.offset_z),
        }
        if r.source_id and not _is_synthetic(r.source_id):
            a['region'] = r.source_id
        elem = ET.Element('translate', **a)
        if r.source_id and _is_synthetic(r.source_id):
            source_elem = regions.get(r.source_id)
            if source_elem is not None:
                elem.append(_region_elem_inline(source_elem))
        return elem

    elif isinstance(r, Everywhere):
        return ET.Element('everywhere', **attrs)

    elif isinstance(r, Above):
        return ET.Element('above', **{**attrs, 'y': _coord(r.y)})

    elif isinstance(r, Half):
        return ET.Element('half', **{
            **attrs,
            'origin': _coords3(r.origin_x, r.origin_y, r.origin_z),
            'normal': _coords3(r.normal_x, r.normal_y, r.normal_z),
        })

    return None


def _region_elem_inline(r: Region) -> ET.Element:
    """Serialize a region without id (for truly anonymous inline use)."""
    dummy_counts: dict[str, int] = {}
    dummy_top: set[str] = set()
    result = _region_elem(r.id, {r.id: r}, dummy_counts, dummy_top, with_id=False)
    return result if result is not None else ET.Element('region')


# ---------------------------------------------------------------------------
# Apply rules
# ---------------------------------------------------------------------------

def _apply_elem(
    rule: ApplyRule,
    regions: dict[str, Region],
    region_parent_counts: dict[str, int],
    top_level_ids: set[str],
    index: int,
) -> ET.Element:
    attrs: dict = {}
    if rule.enter_filter:
        attrs['enter'] = rule.enter_filter
    if rule.leave_filter:
        attrs['leave'] = rule.leave_filter
    if rule.block_filter:
        attrs['block'] = rule.block_filter
    if rule.block_place_filter:
        attrs['block-place'] = rule.block_place_filter
    if rule.block_break_filter:
        attrs['block-break'] = rule.block_break_filter
    if rule.block_physics_filter:
        attrs['block-physics'] = rule.block_physics_filter
    if rule.block_place_against_filter:
        attrs['block-place-against'] = rule.block_place_against_filter
    if rule.use_filter:
        attrs['use'] = rule.use_filter
    if rule.filter_id:
        attrs['filter'] = rule.filter_id
    if rule.kit:
        attrs['kit'] = rule.kit
    if rule.lend_kit:
        attrs['lend-kit'] = rule.lend_kit
    if rule.velocity:
        attrs['velocity'] = rule.velocity
    if rule.message:
        attrs['message'] = rule.message

    # Region: named → attribute; synthetic → inline child
    if rule.region_id and not _is_synthetic(rule.region_id):
        attrs['region'] = rule.region_id
        return ET.Element('apply', **attrs)
    else:
        elem = ET.Element('apply', **attrs)
        if rule.region_id and _is_synthetic(rule.region_id):
            region = regions.get(rule.region_id)
            if region is not None:
                container = ET.SubElement(elem, 'region')
                container.append(_region_elem_inline(region))
        return elem


# ---------------------------------------------------------------------------
# Spawners, renewables, block-drops
# ---------------------------------------------------------------------------

def _write_spawners(parent: ET.Element, spawners: list[WoolSpawner]) -> None:
    block = ET.SubElement(parent, 'spawners')
    for s in spawners:
        attrs: dict = {
            'spawn-region': s.spawn_region,
            'player-region': s.player_region,
        }
        if s.delay:
            attrs['delay'] = s.delay
        if s.max_entities is not None:
            attrs['max-entities'] = str(s.max_entities)
        elem = ET.SubElement(block, 'spawner', **attrs)
        for item in s.items:
            item_attrs: dict = {'material': item.material}
            if item.damage:
                item_attrs['damage'] = str(item.damage)
            if item.amount != 1:
                item_attrs['amount'] = str(item.amount)
            ET.SubElement(elem, 'item', **item_attrs)


def _write_renewables(parent: ET.Element, renewables: list[Renewable]) -> None:
    block = ET.SubElement(parent, 'renewables')
    for r in renewables:
        attrs: dict = {'region': r.region_id}
        if r.rate != 1.0:
            attrs['rate'] = str(r.rate)
        if r.renew_filter:
            attrs['renew-filter'] = r.renew_filter
        if r.replace_filter:
            attrs['replace-filter'] = r.replace_filter
        if r.grow:
            attrs['grow'] = 'true'
        ET.SubElement(block, 'renewable', **attrs)


def _write_block_drops(parent: ET.Element, rules: list[BlockDropRule]) -> None:
    block = ET.SubElement(parent, 'block-drops')
    for rule in rules:
        attrs: dict = {}
        if rule.region_id:
            attrs['region'] = rule.region_id
        if rule.filter_id:
            attrs['filter'] = rule.filter_id
        if rule.wrong_tool:
            attrs['wrong-tool'] = 'true'
        rule_elem = ET.SubElement(block, 'rule', **attrs)
        if rule.replacement:
            ET.SubElement(rule_elem, 'replacement').text = rule.replacement
        if rule.items:
            drops = ET.SubElement(rule_elem, 'drops')
            for item in rule.items:
                item_attrs: dict = {'material': item.material}
                if item.damage:
                    item_attrs['damage'] = str(item.damage)
                if item.amount != 1:
                    item_attrs['amount'] = str(item.amount)
                if item.chance != 1.0:
                    item_attrs['chance'] = str(item.chance)
                ET.SubElement(drops, 'item', **item_attrs)


# ---------------------------------------------------------------------------
# Indentation helper (Python 3.8 compatible fallback)
# ---------------------------------------------------------------------------

def _indent(elem: ET.Element, level: int = 0) -> None:
    indent = '\n' + '    ' * level
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = indent + '    '
        if not elem.tail or not elem.tail.strip():
            elem.tail = indent
        for child in elem:
            _indent(child, level + 1)
        if not child.tail or not child.tail.strip():
            child.tail = indent
    else:
        if level and (not elem.tail or not elem.tail.strip()):
            elem.tail = indent
    if not level:
        elem.tail = '\n'
